#############################################################################
# Makefile for building: T3
# Generated by qmake (2.01a) (Qt 4.7.4) on: So. Jan 29 19:57:05 2012
# Project:  T3.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile T3.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -ISource -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lcrypto -lssl -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Source/main.cpp \
		Source/Gui/mainwindow.cpp \
		Source/Functions/crypt.cpp \
		Source/Functions/cryptblowfish.cpp \
		Source/Functions/crypt3des.cpp \
		Source/Functions/sha_api.cpp \
		Source/Helper/errorposition.cpp \
		Source/Functions/cryptaes.cpp \
		Source/Functions/cryptrsa.cpp \
		Source/Controller/controllserver.cpp \
		Source/Model/personenlist.cpp \
		Source/Gui/managingfrienddialog.cpp \
		Source/Model/rsakeypair.cpp \
		Source/Helper/errorlogger.cpp \
		Source/Gui/settings.cpp \
		Source/Helper/filehandler.cpp \
		Source/Helper/userexception.cpp \
		Source/Helper/mainexception.cpp moc_mainwindow.cpp \
		moc_crypt.cpp \
		moc_controllserver.cpp \
		moc_managingfrienddialog.cpp \
		moc_settings.cpp \
		qrc_Icons.cpp
OBJECTS       = main.o \
		mainwindow.o \
		crypt.o \
		cryptblowfish.o \
		crypt3des.o \
		sha_api.o \
		errorposition.o \
		cryptaes.o \
		cryptrsa.o \
		controllserver.o \
		personenlist.o \
		managingfrienddialog.o \
		rsakeypair.o \
		errorlogger.o \
		settings.o \
		filehandler.o \
		userexception.o \
		mainexception.o \
		moc_mainwindow.o \
		moc_crypt.o \
		moc_controllserver.o \
		moc_managingfrienddialog.o \
		moc_settings.o \
		qrc_Icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		T3.pro
QMAKE_TARGET  = T3
DESTDIR       = 
TARGET        = T3

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_managingfrienddialog.h ui_settings.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: T3.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile T3.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile T3.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/T31.0.0 || $(MKDIR) .tmp/T31.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/T31.0.0/ && $(COPY_FILE) --parents Source/Gui/mainwindow.h Source/Functions/crypt.h Source/Functions/cryptblowfish.h Source/Functions/crypt3des.h Source/Functions/sha_api.h Source/Helper/errorposition.h Source/Functions/cryptaes.h Source/Functions/cryptrsa.h Source/Controller/controllserver.h Source/Model/personenlist.h Source/Gui/managingfrienddialog.h Source/Model/rsakeypair.h Source/Helper/errorlogger.h Source/Helper/globalDefines.h Source/Gui/settings.h Source/Helper/filehandler.h Source/Helper/mainexception.h Source/Helper/userexception.h .tmp/T31.0.0/ && $(COPY_FILE) --parents Source/Icons.qrc .tmp/T31.0.0/ && $(COPY_FILE) --parents Source/main.cpp Source/Gui/mainwindow.cpp Source/Functions/crypt.cpp Source/Functions/cryptblowfish.cpp Source/Functions/crypt3des.cpp Source/Functions/sha_api.cpp Source/Helper/errorposition.cpp Source/Functions/cryptaes.cpp Source/Functions/cryptrsa.cpp Source/Controller/controllserver.cpp Source/Model/personenlist.cpp Source/Gui/managingfrienddialog.cpp Source/Model/rsakeypair.cpp Source/Helper/errorlogger.cpp Source/Gui/settings.cpp Source/Helper/filehandler.cpp Source/Helper/userexception.cpp Source/Helper/mainexception.cpp .tmp/T31.0.0/ && $(COPY_FILE) --parents Source/Gui/mainwindow.ui Source/Gui/managingfrienddialog.ui Source/Gui/settings.ui .tmp/T31.0.0/ && (cd `dirname .tmp/T31.0.0` && $(TAR) T31.0.0.tar T31.0.0 && $(COMPRESS) T31.0.0.tar) && $(MOVE) `dirname .tmp/T31.0.0`/T31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/T31.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_crypt.cpp moc_controllserver.cpp moc_managingfrienddialog.cpp moc_settings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_crypt.cpp moc_controllserver.cpp moc_managingfrienddialog.cpp moc_settings.cpp
moc_mainwindow.cpp: Source/Gui/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Source/Gui/mainwindow.h -o moc_mainwindow.cpp

moc_crypt.cpp: Source/Functions/crypt.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Source/Functions/crypt.h -o moc_crypt.cpp

moc_controllserver.cpp: Source/Controller/controllserver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Source/Controller/controllserver.h -o moc_controllserver.cpp

moc_managingfrienddialog.cpp: Source/Gui/managingfrienddialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Source/Gui/managingfrienddialog.h -o moc_managingfrienddialog.cpp

moc_settings.cpp: Source/Gui/settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Source/Gui/settings.h -o moc_settings.cpp

compiler_rcc_make_all: qrc_Icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Icons.cpp
qrc_Icons.cpp: Source/Icons.qrc \
		Source/splash.png \
		Source/Gui/Icons/info.png \
		Source/Gui/Icons/key.png \
		Source/Gui/Icons/winIcon.png \
		Source/Gui/Icons/close.png \
		Source/Gui/Icons/follow.png \
		Source/Gui/Icons/warning.png \
		Source/Gui/Icons/add.png \
		Source/Gui/Icons/loeschen.png \
		Source/Gui/Icons/check.png \
		Source/Gui/Icons/edit.png \
		Source/Gui/Icons/open.png \
		Source/Gui/Icons/help.png
	/usr/bin/rcc -name Icons Source/Icons.qrc -o qrc_Icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_managingfrienddialog.h ui_settings.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_managingfrienddialog.h ui_settings.h
ui_mainwindow.h: Source/Gui/mainwindow.ui
	/usr/bin/uic-qt4 Source/Gui/mainwindow.ui -o ui_mainwindow.h

ui_managingfrienddialog.h: Source/Gui/managingfrienddialog.ui
	/usr/bin/uic-qt4 Source/Gui/managingfrienddialog.ui -o ui_managingfrienddialog.h

ui_settings.h: Source/Gui/settings.ui
	/usr/bin/uic-qt4 Source/Gui/settings.ui -o ui_settings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: Source/main.cpp Source/Gui/mainwindow.h \
		Source/Helper/globalDefines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Source/main.cpp

mainwindow.o: Source/Gui/mainwindow.cpp Source/Gui/mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o Source/Gui/mainwindow.cpp

crypt.o: Source/Functions/crypt.cpp Source/Functions/crypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crypt.o Source/Functions/crypt.cpp

cryptblowfish.o: Source/Functions/cryptblowfish.cpp Source/Functions/cryptblowfish.h \
		Source/Functions/crypt.h \
		Source/Functions/sha_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cryptblowfish.o Source/Functions/cryptblowfish.cpp

crypt3des.o: Source/Functions/crypt3des.cpp Source/Functions/crypt3des.h \
		Source/Functions/crypt.h \
		Source/Functions/sha_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crypt3des.o Source/Functions/crypt3des.cpp

sha_api.o: Source/Functions/sha_api.cpp Source/Functions/sha_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sha_api.o Source/Functions/sha_api.cpp

errorposition.o: Source/Helper/errorposition.cpp Source/Helper/errorposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorposition.o Source/Helper/errorposition.cpp

cryptaes.o: Source/Functions/cryptaes.cpp Source/Functions/cryptaes.h \
		Source/Functions/crypt.h \
		Source/Functions/sha_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cryptaes.o Source/Functions/cryptaes.cpp

cryptrsa.o: Source/Functions/cryptrsa.cpp Source/Functions/cryptrsa.h \
		Source/Functions/crypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cryptrsa.o Source/Functions/cryptrsa.cpp

controllserver.o: Source/Controller/controllserver.cpp Source/Controller/controllserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controllserver.o Source/Controller/controllserver.cpp

personenlist.o: Source/Model/personenlist.cpp Source/Model/personenlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o personenlist.o Source/Model/personenlist.cpp

managingfrienddialog.o: Source/Gui/managingfrienddialog.cpp Source/Gui/managingfrienddialog.h \
		ui_managingfrienddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managingfrienddialog.o Source/Gui/managingfrienddialog.cpp

rsakeypair.o: Source/Model/rsakeypair.cpp Source/Model/rsakeypair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rsakeypair.o Source/Model/rsakeypair.cpp

errorlogger.o: Source/Helper/errorlogger.cpp Source/Helper/errorlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorlogger.o Source/Helper/errorlogger.cpp

settings.o: Source/Gui/settings.cpp Source/Gui/settings.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o Source/Gui/settings.cpp

filehandler.o: Source/Helper/filehandler.cpp Source/Helper/filehandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filehandler.o Source/Helper/filehandler.cpp

userexception.o: Source/Helper/userexception.cpp Source/Helper/userexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userexception.o Source/Helper/userexception.cpp

mainexception.o: Source/Helper/mainexception.cpp Source/Helper/mainexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainexception.o Source/Helper/mainexception.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_crypt.o: moc_crypt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_crypt.o moc_crypt.cpp

moc_controllserver.o: moc_controllserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controllserver.o moc_controllserver.cpp

moc_managingfrienddialog.o: moc_managingfrienddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_managingfrienddialog.o moc_managingfrienddialog.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

qrc_Icons.o: qrc_Icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Icons.o qrc_Icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

